App/Controllers/SolutionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Models;
using App.DAL;
using App.Enums;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class SolutionEventArgs : EventArgs
    {
        public readonly Solution After;
        public readonly CrudEventEnumStatus Status;

        public SolutionEventArgs(Solution after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class SolutionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<SolutionEventArgs> AfterCall;

        protected virtual void OnCrudOperation(SolutionEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solution solution = db.Solutions.Find(id);
            ViewBag.Id = id;
            if (solution == null)
            {
                return HttpNotFound();
            }
            return View(solution);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Solution solution)
        {
            if (ModelState.IsValid)
            {
                solution.CreatorId = User.Identity.GetUserId();

                db.Solutions.Add(solution);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new SolutionEventArgs(solution, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan Solution";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = solution.Id});
            }

            TempData["Alert"] = "Gagal menambahkan Solution. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(solution);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solution solution = db.Solutions.Find(id);
            ViewBag.Id = id;

            if (solution == null)
            {
                return HttpNotFound();
            }

            return View(solution);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Solution solution)
        {
            if (ModelState.IsValid)
            {
                db.Entry(solution).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new SolutionEventArgs(solution, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan Solution";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = solution.Id});
            }
            ViewBag.Id = solution.Id;

            TempData["Alert"] = "Gagal melakukan perubahan Solution. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(solution);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Solution solution = db.Solutions.Find(id);
            ViewBag.Id = id;

            if (solution == null)
            {
                return HttpNotFound();
            }
            return View(solution);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Solution solution = db.Solutions.Find(id);
            ViewBag.Id = id;
            db.Solutions.Remove(solution);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new SolutionEventArgs(solution, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Models;
using App.DAL;
using App.Enums;
using Microsoft.AspNet.Identity;

namespace App.Controllers
{
    public class TicketEventArgs : EventArgs
    {
        public readonly Ticket After;
        public readonly CrudEventEnumStatus Status;

        public TicketEventArgs(Ticket after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class TicketController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<TicketEventArgs> AfterCall;

        protected virtual void OnCrudOperation(TicketEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            ViewBag.Id = id;
            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticket.CreatorId = User.Identity.GetUserId();
                db.Tickets.Add(ticket);

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new TicketEventArgs(ticket, CrudEventEnumStatus.Create));

                if (!string.IsNullOrWhiteSpace(Request.QueryString["createNext"]))
                {
                    if (Request.QueryString["createNext"] == "true")
                    {
                        TempData["Created"] = true;
                        TempData["Alert"] = "Berhasil menambahkan Ticket";
                        TempData["AlertClass"] = "success";

                        return RedirectToAction("Create");
                    }
                }

                return RedirectToAction("Details", new { id = ticket.Id});
            }

            TempData["Alert"] = "Gagal menambahkan Ticket. Harap periksa kembali data yang anda input.";
            TempData["AlertClass"] = "danger";

            return View(ticket);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ticket ticket = db.Tickets.Find(id);
            ViewBag.Id = id;

            if (ticket == null)
            {
                return HttpNotFound();
            }

            return View(ticket);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ticket).State = EntityState.Modified;

                db.SaveChanges(User.Identity.GetUserName());

                OnCrudOperation(new TicketEventArgs(ticket, CrudEventEnumStatus.Update));

                TempData["Alert"] = "Berhasil menyimpan perubahan Ticket";
                TempData["AlertClass"] = "success";

                return RedirectToAction("Details", new { id = ticket.Id});
            }
            ViewBag.Id = ticket.Id;

            TempData["Alert"] = "Gagal melakukan perubahan Ticket. Harap periksa kembali data yang anda masukkan.";
            TempData["AlertClass"] = "danger";

            return View(ticket);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ticket ticket = db.Tickets.Find(id);
            ViewBag.Id = id;

            if (ticket == null)
            {
                return HttpNotFound();
            }
            return View(ticket);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ticket ticket = db.Tickets.Find(id);
            ViewBag.Id = id;
            db.Tickets.Remove(ticket);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new TicketEventArgs(ticket, CrudEventEnumStatus.Delete));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

App/Controllers/WebApi/SolutionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Kendo.DynamicLinq;
using Newtonsoft.Json;
using Domain.Models;
using App.DAL;
using App.Enums;
using App.Helper;
using Domain.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace App.Controllers.WebApi
{
    public class SolutionsControllerEventArgs : EventArgs
    {
        public readonly Solution After;
        public readonly CrudEventEnumStatus Status;

        public SolutionsControllerEventArgs(Solution after, CrudEventEnumStatus status)
        {
            this.After = after;
            this.Status = status;
        }
    }

    public class SolutionsController : ApiController
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public static event EventHandler<SolutionsControllerEventArgs> AfterCall;

        protected virtual void OnCrudOperation(SolutionsControllerEventArgs e)
        {
            if (AfterCall != null)
            {
                AfterCall(this, e);
            }
        }

        // GET: api/Solutions
        public DataSourceResult GetSolutions(HttpRequestMessage requestMessage)
        {
            DataSourceRequest request =
                JsonConvert.DeserializeObject<DataSourceRequest>(requestMessage.RequestUri.ParseQueryString().GetValues("q")[0]);

            if (request.Filter != null && !request.Filter.Filters.Any())
            {
                request.Filter = null;
            }
            else
            {
                request.Filter.ToCustomExpression();
            }

            var result = db.Solutions.Include(x => x.Creator).Include(x => x.Tickets).AsQueryable();

            return result
                .OrderBy(x => x.Id)
                .Project()
                .To<SolutionViewModel>()
                .ToDataSourceResult(request.Take, request.Skip, request.Sort, request.Filter);
        }

        // GET: api/Solutions/5
        [ResponseType(typeof(SolutionViewModel))]
        public IHttpActionResult GetSolution(int id)
        {
            Solution solution = db.Solutions.Find(id);
            if (solution == null)
            {
                return NotFound();
            }

            return Ok(Mapper.Map<Solution, SolutionViewModel>(solution));
        }

        // PUT: api/Solutions/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutSolution(int id, SolutionViewModel solution)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != solution.Id)
            {
                return BadRequest();
            }

            var tempsolution = solution.ToEntity();

            db.Entry(tempsolution).State = EntityState.Modified;

            try
            {
                db.SaveChanges(User.Identity.GetUserName());
                OnCrudOperation(new SolutionsControllerEventArgs(tempsolution, CrudEventEnumStatus.Update));
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!SolutionExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/Solutions
        [ResponseType(typeof(SolutionViewModel))]
        public IHttpActionResult PostSolution(SolutionViewModel solution)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            var tempsolution = solution.ToEntity();

            db.Solutions.Add(tempsolution);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new SolutionsControllerEventArgs(tempsolution, CrudEventEnumStatus.Create));

            return CreatedAtRoute("DefaultApi", new { id = solution.Id }, 
                    Mapper.Map<Solution, SolutionViewModel>(tempsolution));
        }

        // DELETE: api/Solutions/5
        [ResponseType(typeof(SolutionViewModel))]
        public IHttpActionResult DeleteSolution(int id)
        {
            Solution solution = db.Solutions.Find(id);
            if (solution == null)
            {
                return NotFound();
            }

            db.Solutions.Remove(solution);
            db.SaveChanges(User.Identity.GetUserName());
            OnCrudOperation(new SolutionsControllerEventArgs(solution, CrudEventEnumStatus.Delete));

            return Ok(Mapper.Map<Solution, SolutionViewModel>(solution));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool SolutionExists(int id)
        {
            return db.Solutions.Count(e => e.Id == id) > 0;
        }
    }
}

App/Views/Solution/Create.cshtml
@model Domain.Models.Solution

@{
    ViewBag.Title = "Create";
    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-plus-circle"></span> <strong>Solution - Create</strong>
        </h2>
    </div>
    <div class="panel-content">
    @using (Html.BeginForm("Create", "Solution", FormMethod.Post, new { @id = "formCreate" })) 
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                    @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Title, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                        </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Content, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
            </div>

                @*<div class="form-group">
                    @Html.LabelFor(model => model.CreatorId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                            @Html.DropDownList("CreatorId", new SelectList(new List<string>()), htmlAttributes: new { @class = "form-control kendo-dropdownlist", @id = "CreatorId" })
                                @Html.ValidationMessageFor(model => model.CreatorId, "", new { @class = "text-danger" })
                        </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CreatedAt, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
                        </div>
            </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.LastUpdateTime, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastUpdateTime, new { @class = "form-control form-white" })
                            @Html.ValidationMessageFor(model => model.LastUpdateTime, "", new { @class = "text-danger" })
                        </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsPublished, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                        @Html.EditorFor(model => model.IsPublished)
                                @Html.ValidationMessageFor(model => model.IsPublished, "", new { @class = "text-danger" })
                                </div>
                    </div>
            </div>

                <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="k-button" /> &nbsp; <button type="submit" value="true" name="createNext" class="k-button k-primary">Save and create next</button>
                </div>
            </div>
        </div>
    }
    </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Solution List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br/>
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $("#formCreate").validate({
            rules: {
                Title: {
                    required: true,
                },
                Content: {
                    required: true,
                },
                CreatorId: {
                },
                CreatedAt: {
                },
                LastUpdateTime: {
                },
                IsPublished: {
                },
            }
        });

        $(".kendo-dropdownlist").kendoDropDownList({
            filter: "contains"
        });

        $("button[name='createNext']").click(function (e) {
            var url = $("#formCreate").attr("action") + "?createNext=true";
            $("#formCreate").attr("action", url);
        });

        var dsCreatorId = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)Creators",
                    dataType: "json",
                    contentType: "application/json",
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        
                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            pageSize: 7
        });

        $("#CreatorId").kendoDropDownList({
            filter: "contains",
            dataSource: dsCreatorId,
            dataTextField: "Email",
            dataValueField: "Id",
        });

        $(".kendo-datetimepicker").kendoDateTimePicker({
            format: "yyyy-MM-dd HH:mm"
        });
    </script>
}

App/Views/Solution/Details.cshtml
@model Domain.Models.Solution

@{
    ViewBag.Title = "Details";

    var webApiUrl = System.Configuration.ConfigurationManager.AppSettings["webApiUrl"];
}

<div class="panel">
    <div class="panel-header border-bottom">
        <h2>
            <span class="fa fa-info-circle"></span> <strong>Solution - Details</strong>
        </h2>
    </div>
    <div class="panel-content">
        <dl class="dl-horizontal">
                    <dt>
                @Html.DisplayNameFor(model => model.Creator)
            </dt>

            <dd>
                @*<a href="@Url.Action("Details", "ApplicationUser", new { id = Model.Creator.Id })" >@Model.Creator.Email</a>*@
                @if (Model.CreatorId == null)
                {
                    <span class='text'>Anonymous</span>
                }
                else
                { <a href="@Url.Action("Details", "ApplicationUser", new { id = Model.Creator.Id })">@Model.Creator.Email</a> }
            </dd>
                        <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.Content)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Content)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.LastUpdateTime)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.LastUpdateTime)
            </dd>
                    <dt>
                @Html.DisplayNameFor(model => model.IsPublished)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsPublished)
            </dd>
            </dl>
            <div id="tabstrip">
            <ul>
                    <li class="k-state-active">
                    Tickets
                </li>
                    <li class="">
                    Logs
                </li>
                </ul>
                <div id="grid-Tickets"></div>
                <div id="grid-logs"></div>
            </div>
        <div style="height: 20px;"></div>
        </div>
    <div class="panel-footer">
        <p class="pull-right">
            @Html.ActionLink("Edit", "Edit", new { id = ViewBag.Id }) |
            @Html.ActionLink("Solution List", "Index")
            @if (Request.UrlReferrer != null)
            {
                @: | <a class="bottomNav" onclick="history.go(-1); return false;" href="#">Back</a><br />
            }
        </p>
        <div class="clearfix"></div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function() {
            $("#tabstrip").kendoTabStrip({
                animation:  {
                    open: {
                        effects: "fadeIn"
                    }
                }
            });
        });
        var dsTickets = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)Tickets",
                    dataType: "json",
                    contentType: "application/json"
                },
                parameterMap: function (options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id'
                }
            },
            filter: {
                field: "SolutionId",
                operator: "eq",
                value: parseInt("@ViewBag.Id")
            },
            serverFiltering: true,
            serverPaging: true,
            serverSorting: true,
            pageSize: 10
        });

        $("#grid-Tickets").kendoGrid({
            dataSource: dsTickets,
            dataBound: gridDataBound,
            noDataMessage: 'Currently no Tickets available',
            sortable: true,
            filterable: {
                mode: "row"
            },
            pageable:{
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            groupable: true,
            columns: [
                {
                    field: "Creator.Email",
                    title: "Creator",
                    template: function (data) {
                        var html = "<div class='text-center'>";
                        if (data.CreatorId == null) {
                            html += "<span class='text-center'>" + "Null" + "</span>";
                        } else {
                            html += '<a href="@Url.Action("Details","ApplicationUser")/' + data.Creator.Id + '">' + data.Creator.Email + '</a>';
                        }
                        html += "</div>";
                        return html;
                       //s return '<a href="@Url.Action("Details","ApplicationUser")/' + data.Creator.Id + '">' + data.Creator.Email + '</a>';
                    }
                },
                "Title",
                "Description",
                "Category",
                "Status",
                "Application",
                "Priority",
                {
                    field: "DueDate",
                    format: "{0: yyyy-MM-dd HH:mm:ss}"
                },
                {
                    field: "CreatedAt",
                    format: "{0: yyyy-MM-dd HH:mm:ss}"
                },
                {
                    field: "LastUpdateTime",
                    format: "{0: yyyy-MM-dd HH:mm:ss}"
                },
                {
                    command: [
                        {
                            name: 'Details',
                            click: function (data) {
                                var dataItem = this.dataItem($(data.currentTarget).closest("tr"));
                                window.location = "@Url.Action("Details", "Ticket")/" + dataItem.Id;
                            },
                            text: "<button class='btn btn-default btn-transparent btn-sm p-0' title='Details'><span class='fa fa-search'></span></button>"
                        }
                    ],
                    width: 100
                }
            ]
        });

        var dsLogs = new kendo.data.DataSource({
            type: "json",
            transport: {
                read: {
                    url: "@(webApiUrl)logs/Solutions/@ViewBag.Id",
                    dataType: "json",
                    contentType: "application/json"
                },
                parameterMap: function(options, operation) {
                    if (operation === "destroy") {
                        return null;
                    } else if (operation !== "read" && options.models) {
                        return { models: kendo.stringify(options.models) };
                    } else {
                        return "q=" + JSON.stringify(options);
                    }
                }
            },
            schema: {
                data: "Data",
                total: "Total",
                model: {
                    id: 'Id',
                    fields: {
                        EventDateUTC: {
                            type: "date"
                        }
                    }
                }
            },
            serverFiltering: true,
            serverPaging: true,
            serverSorting: true,
            pageSize: 10
        });

        $("#grid-logs").kendoGrid({
            dataSource: dsLogs,
            sortable: true,
            filterable: {
                mode: "row"
            },
            pageable: {
                refresh: true,
                pageSizes: true,
                buttonCount: 5
            },
            groupable: true,
            columns: [
                {
                    field: "EventType",
                    title: "Type"
                },
                {
                    field: "EventDateUTC",
                    title: "Change Date",
                    format: "{0: yyyy-MM-dd HH:mm:ss}"
                },
                {
                    field: "ColumnName",
                    title: "Column"
                },
                {
                    field: "OriginalValue",
                    title: "Original"
                },
                {
                    field: "NewValue",
                    title: "New"
                },
                {
                    field: "UserName",
                    title: "By"
                }
            ]
        });
    </script>
}